apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
  - name: {{  .Values.redis.service.name  }}
    port: {{  .Values.redis.service.servicePort  }}
    protocol: TCP
    targetPort: {{  .Values.redis.service.targetPort  }}
  selector:
    app: redis
  type: {{  .Values.redis.service.type  }}
status:
  loadBalancer: {}
