apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: {{  .Values.redis.replicaCount  }}
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: {{  .Values.redis.image.repository  }}:{{  .Values.redis.image.tag  }}
        imagePullPolicy: {{  .Values.redis.image.pullPolicy  }}
        name: redis
        resources: {}
status: {}
