apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: {{  .Values.result.replicaCount  }}
  selector:
    matchLabels:
      app: result
  strategy: {}
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: {{  .Values.result.image.repository  }}/{{  .Values.result.image.tag  }}
        imagePullPolicy: {{  .Values.result.image.pullPolicy  }}
        name: vote-result
        resources: {}
status: {}
