apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  ports:
  - name: {{  .Values.result.service.name  }}
    nodePort: {{  .Values.result.service.nodePort  }}
    port: {{  .Values.result.service.servicePort  }}
    protocol: TCP
    targetPort: {{  .Values.result.service.targetPort  }}
  selector:
    app: result
  type: {{  .Values.result.service.type  }}
status:
  loadBalancer: {}
