apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: {{  .Values.vote.replicaCount  }}
  selector:
    matchLabels:
      app: vote
  strategy: {}
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: {{  .Values.vote.image.repository  }}/{{  .Values.vote.image.tag  }}
        imagePullPolicy: {{  .Values.vote.image.pullPolicy  }}
        name: vote
        resources: {}
status: {}
